var AppConfig = {
    url: "",
    getUserUrl:'/buyflowApp/server/getUser.jsx',
    selectRulesUrl: "/buyflowApp/server/selectRules.jsx",
    selectOrderRuleUrl: "/buyflowApp/server/selectOrderRuleForItem.jsx",
    setCheckedItemsUrl:"/buyflowApp/server/setCheckedItems.jsx",
    orderFormPageUrl:"/buyflowApp/orderForm.jsx",
    orderFormUrl:"/buyflowApp/server/order/orderForm.jsx",
    saveAddressUrl: "/buyflowApp/server/order/saveAddress.jsx",
    addressListUrl : "/buyflowApp/server/order/addressList.jsx",
    deleteAddressUrl:"/buyflowApp/server/order/deleteAddress.jsx",
    updateAddressUserNameUrl:"/buyflowApp/server/order/updateAddressUserName.jsx",
    getInvoiceListUrl:"/buyflowApp/server/order/getInvoiceList.jsx",
    deleteInvoiceUrl:"/buyflowApp/server/order/deleteInvoice.jsx",
    saveInvoiceUrl:"/buyflowApp/server/order/saveInvoice.jsx",
    saveSelectedPaymentUrl:"/buyflowApp/server/order/saveSelectedPayment.jsx",
    setDefaultInvoiceUrl:"/buyflowApp/server/order/setDefaultInvoice.jsx",
    setDefaultAddressUrl:"/buyflowApp/server/order/setDefaultAddress.jsx",
    addOrderUrl : "/buyflowApp/server/order/addOrder.jsx",
    getFreeCardList:"/buyflowApp/server/getFreeCardList.jsx",
    sonAddOrderUrl : "/ewjAppTemplate/serverHandlers/sonAddOrder.jsx",
    setSelectedDeliveryRuleUrl : "/buyflowApp/server/order/setSelectedDeliveryRule.jsx",
    saveSelectedPaymentAndDeliveryRuleUrl : "/buyflowApp/server/order/saveSelectedPaymentAndDelivery.jsx",
    setLowPricePresentUrl:"/buyflowApp/server/setLowPricePresent.jsx",
    getRegionLevelsUrl:"/buyflowApp/server/order/getRegionLevels.jsx",
    getRegionChildrenUrl:"/buyflowApp/server/order/getRegionChildren.jsx",
    getSkusUrl:"/buyflowApp/server/getSkus.jsx",
    setCartSkuUrl:"/buyflowApp/server/setCartSku.jsx",
    getServerTimeUrl:"buyflowApp/server/getServerTime.jsx",
    payUrl : "pages/payOrders.jsx",
    jiaJuQuanPayUrl : "/buyflowApp/pages/jiaJuQuanPayOrders.jsx",
    cartUrl : "/cart.html",
    loginUrl : "/login/sign_in.jsp?redirectURL="+ location.href,
    spec:"80X80",
    leftCashPayAmount:0
};