function App(a,b,c,d){this.name=ko.observable(a);this.description=ko.observable(b);this.icon=ko.observable(c);this.appId=ko.observable(d)}
function RightsTemplate(a){a=a||{};var b=this;this.id=ko.observable(a.id);this.name=ko.observable(a.name);this.description=ko.observable(a.description);this.apps=ko.observableArray();if(a.apps){var c=$.map(a.apps,function(a){return new App(a.name,a.description,a.icon,a.appId)});this.apps(c)}this.maxProductNumber=ko.observable(a.maxProductNumber);this.setData=function(a){b.id(a.id);b.name(a.name);b.description(a.description);b.maxProductNumber(a.maxProductNumber);a.apps?(a=$.map(a.apps,function(a){return new App(a.name,
a.description,a.icon,a.appId)}),b.apps(a)):b.apps([])};this.editUrl=ko.computed(function(){return"#/rightsTemplate/edit/"+b.id()})}
function RightsTemplateFormViewModel(){var a=this;a.template=new RightsTemplate;a.availableApps=ko.observableArray();a.getAvailableApps=function(){$.post("server/rightsTemplate/getAvailableApps.jsx",{m:m},function(b){"ok"==b.state&&a.availableApps($.map(b.apps,function(a){return new App(a.name,a.description,a.icon,a.appId)}))},"json")};a.leftApps=ko.computed(function(){var b=[],c=a.template.apps(),d=a.availableApps();$.each(d,function(a,d){for(var g=!1,f=c.length-1;0<=f;f--)if(c[f].appId()==d.appId()){g=
!0;console.log(d.appId());break}g||b.push(d)});return b});a.addApp=function(b){a.template.apps.push(b)};a.deleteApp=function(b){a.template.apps.remove(b)};a.setTemplateId=function(b){b?$.post("server/rightsTemplate/getTemplate.jsx",{m:m,id:b},function(b){"ok"==b.state?a.template.setData(b.template):bootbox.alert("\u51fa\u9519\u4e86\uff1a"+b.msg)},"json"):a.template.setData({})};a.save=function(){var b=ko.mapping.toJS(a.template);$.post("server/rightsTemplate/saveTemplate.jsx",{m:m,template:JSON.stringify(b)},
function(b){"ok"==b.state?(a.template.id(b.id),bootbox.alert("\u4fdd\u5b58\u6210\u529f\u3002")):bootbox.alert("\u4fdd\u5b58\u5931\u8d25\u3002")},"json")};a.getAvailableApps()}var rightsTemplateFormPage=null;$(document).ready(function(){rightsTemplateFormPage=new RightsTemplateFormViewModel;ko.applyBindings(rightsTemplateFormPage,document.getElementById("rightsTemplateForm"))});
function RightsTemplateListViewModel(){var a=this;this.templates=ko.observableArray();this.getAllTemplates=function(){$.post("server/rightsTemplate/getAllTemplates.jsx",{m:m},function(b){"ok"==b.state&&(b=$.map(b.templates,function(a){return new RightsTemplate(a)}),a.templates(b))},"json")};this.getAllTemplates();this.deleteTemplate=function(b){$.post("server/rightsTemplate/deleteTemplate.jsx",{m:m,id:b.id()},function(b){"ok"==b.state?(bootbox.alert("\u5220\u9664\u6210\u529f\u3002"),a.getAllTemplates()):
bootbox.alert("\u5220\u9664\u5931\u8d25\uff01")},"json")}}var rightsTemplateListPage=null;$(document).ready(function(){rightsTemplateListPage=new RightsTemplateListViewModel;ko.applyBindings(rightsTemplateListPage,document.getElementById("rightsTemplateListPage"))});
function RightsDispatchRule(a){a=a||{};var b=this;b.id=ko.observable(a.id);b.name=ko.observable(a.name);b.description=ko.observable(a.description);b.orgId=ko.observable(a.orgId);b.orgName=ko.observable(a.orgName);b.levelId=ko.observable(a.levelId);b.levelName=ko.observable(a.levelName);b.mainCategoryId=ko.observable(a.mainCategoryId);b.mainCategoryName=ko.observable(a.mainCategoryName);b.customCategoryId=ko.observable(a.customCategoryId);b.customCategoryName=ko.observable(a.customCategoryName);b.templateId=
ko.observable(a.templateId);b.templateName=ko.observable(a.templateName);b.setData=function(a){b.id(a.id);b.name(a.name);b.description(a.description);b.orgId(a.orgId);b.orgName(a.orgName);b.levelId(a.levelId);b.levelName(a.levelName);b.mainCategoryId(a.mainCategoryId);b.mainCategoryName(a.mainCategoryName);b.customCategoryId(a.customCategoryId);b.customCategoryName(a.customCategoryName);b.templateId(a.templateId);b.templateName(a.templateName)};this.editUrl=ko.computed(function(){return"#/rightsDispatchRule/edit/"+
b.id()})}
function RuleListViewModel(){var a=this;a.rules=ko.observableArray();a.getRules=function(){$.post("server/rightsDispatchRule/getRules.jsx",{m:m},function(b){"ok"==b.state?(b=$.map(b.rules,function(a){return new RightsDispatchRule(a)}),a.rules(b)):bootbox.alert("\u51fa\u9519\u4e86\uff01"+b.msg)},"json")};this.deleteRule=function(b){bootbox.confirm("\u786e\u5b9a\u5220\u9664\uff1f",function(c){c&&$.post("server/rightsDispatchRule/deleteRule.jsx",{m:m,id:b.id()},function(b){"ok"==b.state?(bootbox.alert("\u5220\u9664\u6210\u529f\u3002"),a.getRules()):
bootbox.alert("\u5220\u9664\u5931\u8d25\uff01")},"json")})}}var ruleListPage=null;$(document).ready(function(){ruleListPage=new RuleListViewModel;ko.applyBindings(ruleListPage,document.getElementById("ruleListPage"))});var ruleFormPage=null,selectColumnDialog=null;
function SelectColumnDialog(){var a=this;a.title=ko.observable();a.itemPath=ko.observableArray();a.itemChildren=ko.observableArray();a.fromId="";a.callback=null;a.open=function(b,c,d,e){a.title(d);a.fromId=c;a.callback=e;$.post("server/rightsDispatchRule/getItemInfo.jsx",{id:b,fromId:c,m:m},function(b){"ok"==b.state&&(a.itemPath($.map(b.itemPath,function(a){return new ColumnItem(a)})),a.itemChildren($.map(b.itemChildren,function(a){return new ColumnItem(a)})))},"json");$("#selectColumnDialog").modal("show")};
a.setCurrentItem=function(b){a.open(b.id,a.fromId,a.title(),a.callback)};a.isEmpty=ko.computed(function(){return 0==a.itemChildren().length});a.onOk=function(){var b="",c="";$.each(a.itemPath(),function(a,e){b=b+">"+e.name;c=e.id});a.callback(b,c);$("#selectColumnDialog").modal("hide")}}
function RuleFormViewModel(){var a=this;a.rule=new RightsDispatchRule({});a.setOrg=function(b,c){a.rule.orgName(b);a.rule.orgId(c)};a.setLevel=function(b,c){a.rule.levelId(c);a.rule.levelName(b)};a.setMainCategory=function(b,c){a.rule.mainCategoryId(c);a.rule.mainCategoryName(b)};a.setCustomCategory=function(b,c){a.rule.customCategoryId(c);a.rule.customCategoryName(b)};a.selectOrg=function(){selectColumnDialog.open("col_merchant_all","col_merchant_all","\u9009\u62e9\u7ec4\u7ec7\u673a\u6784",a.setOrg)};
a.selectLevel=function(){selectColumnDialog.open("col_merchant_merchantgrade","col_merchant_merchantgrade","\u9009\u62e9\u5546\u5bb6\u7b49\u7ea7",a.setLevel)};a.selectMainCategory=function(){selectColumnDialog.open("col_merchant_sort","col_merchant_sort","\u9009\u62e9\u5546\u5bb6\u4e3b\u5206\u7c7b",a.setMainCategory)};a.selectCustomCategory=function(){selectColumnDialog.open("col_merchant_othersort","col_merchant_othersort","\u9009\u62e9\u5546\u5bb6\u81ea\u5b9a\u4e49\u5206\u7c7b",a.setCustomCategory)};
a.save=function(){a.rule.templateId(a.selectedTemplate());$.each(a.templates(),function(b,d){d.id()==a.selectedTemplate()&&a.rule.templateName(d.name())});var b=ko.mapping.toJS(a.rule);$.post("server/rightsDispatchRule/saveRule.jsx",{m:m,rule:JSON.stringify(b)},function(b){"ok"==b.state?(a.rule.id(b.id),bootbox.alert("\u4fdd\u5b58\u6210\u529f\u3002")):bootbox.alert("\u4fdd\u5b58\u5931\u8d25\u3002")},"json")};a.setRuleId=function(b){$.post("server/rightsDispatchRule/getRuleById.jsx",{m:m,id:b},function(b){"ok"==
b.state?(a.rule.setData(b.rule),a.selectedTemplate(a.rule.templateId())):bootbox.alert("\u51fa\u9519\u4e86\u3002"+b.msg)},"json")};a.templates=ko.observableArray();a.getAllTemplates=function(){$.post("server/rightsTemplate/getAllTemplates.jsx",{m:m},function(b){"ok"==b.state&&(b=$.map(b.templates,function(a){return new RightsTemplate(a)}),a.templates(b))},"json")};a.selectedTemplate=ko.observable();a.selectedTemplate(a.rule.templateId());a.getAllTemplates()}
function ColumnItem(a){this.name=a.name;this.id=a.id}$(document).ready(function(){ruleFormPage=new RuleFormViewModel;selectColumnDialog=new SelectColumnDialog;ko.applyBindings(selectColumnDialog,document.getElementById("selectColumnDialog"));ko.applyBindings(ruleFormPage,document.getElementById("rightsDispatchRuleForm"))});
var sammyApp=$.sammy(function(){this.get("#/rightsTemplate/list",function(a){$(".page").hide();$("#rightsTemplateListPage").fadeIn();$(".module").removeClass("active");$("#rightsTemplateModule").addClass("active");rightsTemplateListPage.getAllTemplates()});this.get("#/rightsTemplate/add",function(a){$(".page").hide();rightsTemplateFormPage.setTemplateId(null);$("#rightsTemplateForm").fadeIn();$(".module").removeClass("active");$("#rightsTemplateModule").addClass("active")});this.get("#/rightsTemplate/edit/:templateId",
function(a){a=this.params.templateId;$(".page").hide();rightsTemplateFormPage.setTemplateId(a);$("#rightsTemplateForm").fadeIn();$(".module").removeClass("active");$("#rightsTemplateModule").addClass("active")});this.get("#/rightsDispatch/list",function(a){$(".page").hide();$("#ruleListPage").fadeIn();$(".module").removeClass("active");$("#rightsDispatchModule").addClass("active");ruleListPage.getRules()});this.get("#/rightsDispatchRule/add",function(a){$(".page").hide();$("#rightsDispatchRuleForm").fadeIn();
$(".module").removeClass("active");ruleFormPage.getAllTemplates();$("#rightsDispatchModule").addClass("active")});this.get("#/rightsDispatchRule/edit/:ruleId",function(a){a=this.params.ruleId;$(".page").hide();$("#rightsDispatchRuleForm").fadeIn();$(".module").removeClass("active");ruleFormPage.getAllTemplates();$("#rightsDispatchModule").addClass("active");ruleFormPage.setRuleId(a)})});$(document).ready(function(){bootbox.setDefaults({locale:"zh_CN"});sammyApp.run("#/rightsTemplate/list")});
